### ISSUE TITLE
Some errors now on 10.0 patch.

### ISSUE THREAD

**Issue by Rhindle7** [kethowow/ScrollingChatText#1]
9x ...rface/AddOns/ScrollingChatText/ScrollingChatText.lua:419: table index is nil
[string "@Interface/AddOns/ScrollingChatText/ScrollingChatText.lua"]:419: in main chunk

Locals:
NAME = "ScrollingChatText"
S = <table> {
 GetTimestamp = <function> defined @Interface/AddOns/ScrollingChatText/ScrollingChatText.lua:398
 GetClassIcon = <function> defined @Interface/AddOns/ScrollingChatText/ScrollingChatText.lua:361
 playerCache = <table> {
 }
 eventremap = <table> {
 }
 ColorOptions = <table> {
 }
 LibSinkChat = <table> {
 }
 OtherEvents = <table> {
 }
 colorremap = <table> {
 }
 L = <table> {
 }
 EventToColor = <table> {
 }
 timestamps = <table> {
 }
 revLOCALIZED_CLASS_NAMES = <table> {
 }
 classCache = <table> {
 }
 MONSTER_CHAT = <table> {
 }
 sexName = <table> {
 }
 playerName = "Liminal"
 chatCache = <table> {
 }
 GetRaceIcon = <function> defined @Interface/AddOns/ScrollingChatText/ScrollingChatText.lua:355
 otherremap = <table> {
 }
 INFORM = <table> {
 }
 MONSTER_EMOTE = <table> {
 }
 events = <table> {
 }
 ColorOtherOptions = <table> {
 }
 playerClass = "HUNTER"
 CHANNEL = <table> {
 }
 OtherSubEvents = <table> {
 }
 playerGUID = "Player-3666-0A615F2E"
}
SCR = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 UnregisterAllEvents = <function> defined @Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 EnableModule = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Interface/AddOns/AdiBags/libs/AceConsole-3.0/AceConsole-3.0.lua:107
 Printf = <function> defined @Interface/AddOns/AdiBags/libs/AceConsole-3.0/AceConsole-3.0.lua:65
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 GetSinkAce3OptionsDataTable = <function> defined @Interface/AddOns/!KalielsTracker/Libs/LibSink-2.0/LibSink-2.0.lua:662
 name = "ScrollingChatText"
 IsEnabled = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 Pour = <function> defined @Interface/AddOns/!KalielsTracker/Libs/LibSink-2.0/LibSink-2.0.lua:522
 DisableModule = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 RegisterMessage = <function> defined @Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 Print = <function> defined @Interface/AddOns/AdiBags/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 IsModule = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:464
 WipeCache = <function> defined @Interface/AddOns/ScrollingChatText/ScrollingChatText.lua:344
 SendMessage = <function> defined @Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:54
 RefreshDB1 = <function> defined @Interface/AddOns/ScrollingChatText/ScrollingChatText.lua:10
 S = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 GetSinkAce2OptionsDataTable = <function> defined @Interface/AddOns/!KalielsTracker/Libs/LibSink-2.0/LibSink-2.0.lua:598
 enabledState = true
 SetSinkStorage = <function> defined @Interface/AddOns/!KalielsTracker/Libs/LibSink-2.0/LibSink-2.0.lua:819
 RegisterEvent = <function> defined @Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterAllMessages = <function> defined @Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 RegisterSink = <function> defined @Interface/AddOns/!KalielsTracker/Libs/LibSink-2.0/LibSink-2.0.lua:781
 GetArgs = <function> de

and

1x Interface/AddOns/ScrollingChatText/ScrollingChatText.lua:1 (null)

and 

1x FrameXML\Bindings.xml:1 Interface/AddOns/ScrollingChatText/ScrollingChatText.lua:1 (null)

and 

2x Interface/AddOns/ScrollingChatText/Core.lua:93: attempt to index field 'CombatTextEnabled' (a nil value)
[string "@Interface/AddOns/ScrollingChatText/Core.lua"]:93: in function `OnInitialize'
[string "@Interface/AddOns/ScrollingChatText/Core.lua"]:30: in function <Interface/AddOns/ScrollingChatText/Core.lua:26>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 CHAT_MSG_OTHER = <function> defined @Interface/AddOns/ScrollingChatText/Core.lua:533
 SetSinkStorage = <function> defined @Interface/AddOns/!KalielsTracker/Libs/LibSink-2.0/LibSink-2.0.lua:819
 SetMessage = <function> defined @Interface/AddOns/ScrollingChatText/Options.lua:667
 SlashCommand = <function> defined @Interface/AddOns/ScrollingChatText/Core.lua:210
 modules = <table> {
 }
 baseName = "ScrollingChatText"
 GetChatTypeInfo = <function> defined @Interface/AddOns/ScrollingChatText/Options.lua:133
 WipeCache = <function> defined @Interface/AddOns/ScrollingChatText/ScrollingChatText.lua:344
 Printf = <function> defined @Interface/AddOns/AdiBags/libs/AceConsole-3.0/AceConsole-3.0.lua:65
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 GetSinkAce3OptionsDataTable = <function> defined @Interface/AddOns/!KalielsTracker/Libs/LibSink-2.0/LibSink-2.0.lua:662
 defaultModuleState = true
 IsEnabled = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 DisableModule = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 RegisterMessage = <function> defined @Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 GetArgs = <function> defined @Interface/AddOns/AdiBags/libs/AceConsole-3.0/AceConsole-3.0.lua:140
 RegisterSink = <function> defined @Interface/AddOns/!KalielsTracker/Libs/LibSink-2.0/LibSink-2.0.lua:781
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 enabledState = true
 RefreshDB2 = <function> defined @Interface/AddOns/ScrollingChatText/Options.lua:8
 RegisterEvent = <function> defined @Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 IterateModules = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 SetValueColor = <function> defined @Interface/AddOns/ScrollingChatText/Options.lua:639
 OnInitialize = <function> defined @Interface/AddOns/ScrollingChatText/Core.lua:54
 NewModule = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 GetModule = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Interface/AddOns/AdiBags/libs/AceConsole-3.0/AceConsole-3.0.lua:107
 CHAT_MSG_STATIC = <function> defined @Interface/AddOns/ScrollingChatText/Core.lua:500
 GetName = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 Output = <function> defined @Interface/AddOns/ScrollingChatText/Core.lua:604
 SetValueColorChat = <function> defined @Interface/AddOns/ScrollingChatText/Options.lua:662
 name = "ScrollingChatText"
 ChatOutput = <function> defined @Interface/AddOns/ScrollingChatText/Core.lua:595
 orderedModules = <table> {
 }
 GetSinkAce2OptionsDataTable = <function> defined @Interface/AddOns/!KalielsTracker/Libs/LibSink-2.0/LibSink-2.0.lua:598
 Disable = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 ReplaceArgs = <function> defined @Interface/AddOns/ScrollingChatText/Core.lua:578
 Enable = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 UnregisterAllEvents = <function> defined @Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 Print = <function> defined @Interface/AddOns/AdiBags/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 EnableModule = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 IterateEmbeds = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 CHAT_MSG_BN = <function> defined @Interface/AddOns/ScrollingChatText/Core.lua:429
 RegisterCh

**Comment by Ketho** [comment]
Sorry for the late reply, it should be working again for 10.0
